import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.css'

import Content from "components/content";
import Footer from "components/footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hikaru Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content />

      <Footer />
    </div>
  )
}

export default Home
